### ISSUE TITLE
Run on macOS: Unhandled Exception: SocketException: Send failed (OS Error: Operation not permitted, errno = 1), address = 0.0.0.0, port = 1900

### ISSUE THREAD

**Issue by billcoding** [rwscode/dart_castscreen#3]
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Send failed (OS Error: Operation not permitted, errno = 1), address = 0.0.0.0, port = 1900
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1269:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2582:15)
#2      CastScreen._search (package:castscreen/src/core/core.dart:226:16)
#3      CastScreen._discover (package:castscreen/src/core/core.dart:62:5)
<asynchronous suspension>
#4      CastScreen.discoverDevice (package:castscreen/src/core/core.dart:45:5)
<asynchronous suspension>
#5      _MyHomePageState.search (package:example/main.dart:41:9)
<asynchronous suspension>
```

**Comment by billcoding** [comment]
macOS needs you to request a specific entitlement in order to access the network. To do that open macos/Runner/DebugProfile.entitlements and add the following key-value pair. 
```
<key>com.apple.security.network.client</key>
<true/>
```
Details see:
- [setting-up-entitlements](https://docs.flutter.dev/platform-integration/macos/building#setting-up-entitlements)
- [socketexception-connection-failed-os-error-operation-not-permitted-errno-1](https://stackoverflow.com/questions/65458903/socketexception-connection-failed-os-error-operation-not-permitted-errno-1)
